### ISSUE TITLE
Unable to display Hebrew texts, shows gibberish

### ISSUE THREAD

**Issue by laukstein** [WinMerge/winmerge-v2#163] opened 2019-07-25 16:48 UTC
WinMerge 2.16.2 unable to display Hebrew texts, shows:

![grabilla g10300](https://user-images.githubusercontent.com/183966/61892694-06840480-af15-11e9-9bc6-0952b9e4fe05.png)

**Comment by laukstein** [comment] 2019-07-25 16:52
Just noticed it created debug.log with

    [0725/194414.110:ERROR:crash_report_database_win.cc(469)] failed to stat report

**Comment by sdottaka** [comment] 2019-07-27 00:06
Unfortunately, the current WinMerge does not handle text in Right-to-left languages ​​like Hebrew correctly.
However, when I look at the attached image, it looks like the Hebrew character itself is not displayed. WinMerge should be able to display the Hebrew characters.
Could you attach the text file to reproduce the bug here?

**Comment by laukstein** [comment] 2019-07-27 19:00
@sdottaka, I just checked it again and it works now file, Hebrew chars are now displayed. It seems was some temporal issue, maybe the debug.log can say anything about it `crash_report_database_win.cc(469)`

**Comment by sdottaka** [comment] 2019-08-04 23:20
For now, I will close this issue.
If you find a way to reproduce, please let us know.

**Closed by sdottaka** 2019-08-04 23:20 UTC

**Comment by voidray** [comment] 2022-01-12 07:52
The tool Meld supports comparing Hebrew already. So that might be a solution until WinMerge also supports it. I prefer having only one tool.

**Comment by coldacid** [comment] 2022-04-08 00:02
@voidray so long as you have a font selected which provides Hebrew letters, WinMerge will display them, at least as of the current version.
