### ISSUE TITLE
A crash

### ISSUE THREAD

**Issue by StoyanDimitrov** [WinMerge/winmerge-v2#104] opened 2018-11-07 11:50 UTC
Latest release, Win 10 Home, x64, [default settings](https://github.com/WinMerge/winmerge-v2/files/2422865/remove-winmerge-settings.zip).
STR:
1. Open WinMerge.
2. Open `Edit` > `Options`.
3. Press `Ctrl-N`.
4. In the left pane type:
```
a
a
```
5. Press `F5` to initiate the syntax highlight.
6. In the *very last line*, the grey one, of the right pane type:
```
a
```

### Regarding #80
Using `F5` to kick in the syntax highlight also could be used to emulate the `Automatic rescan` in the STR after step 4. (for previous release version). Both issues seem related but I can not find common STR.

At least now is clear why `Automatic rescan` is needed for the crash.

**Comment by sdottaka** [comment] 2018-11-08 12:32
Thank you for the report.
I could not reproduce the crash when I followed your instructions.

I operated as follows, is it correct?
![issue104](https://user-images.githubusercontent.com/98126/48198835-837a4880-e39d-11e8-848e-9c935ab557df.gif)

However, after that, a crash occurred when some operation was done. It has not been reproduced yet.

**Comment by StoyanDimitrov** [comment] 2018-11-08 12:38
I'm sorry. In step 5 read `F5` instead `Ctrl+F5`. Then the first line in the right pane will be yellow and the second grey. I'll fix the OP

**Comment by sdottaka** [comment] 2018-11-08 15:58
Thank you for the fix. Now I can reproduce the crash. I will look into it.

**Comment by sdottaka** [comment] 2018-11-13 22:47
Fixed in aa4d66b6394bd9def880a02f344f602639495034

**Closed by sdottaka** 2018-11-13 22:47 UTC
